#YAML for Arlec ALD092RHA Downlight
substitutions:
  devname: 'ALD092RHA'

esphome:
  platform: 'ESP8266'
  board: 'esp01_1m'
  name: Arlec ALD092RHA ${devname}
  
output:
  - platform: esp8266_pwm
    id: ${devname}_output_cw
    pin: GPIO4
    frequency: 400 Hz #Adding this will stop flicker at low dimmer levels

  - platform: esp8266_pwm
    id: ${devname}_output_ww
    pin: GPIO5
    frequency: 400 Hz #Adding this will stop flicker at low dimmer levels

  - platform: esp8266_pwm
    id: ${devname}_output_red
    pin: GPIO12

  - platform: esp8266_pwm
    id: ${devname}_output_blue
    pin: GPIO13

  - platform: esp8266_pwm
    id: ${devname}_output_green
    pin: GPIO14

light:
  - platform: rgbww
    name: ${devname} Light
    id: ${devname}_light
    red: ${devname}_output_red
    green: ${devname}_output_green
    blue: ${devname}_output_blue
    cold_white: ${devname}_output_cw
    warm_white: ${devname}_output_ww
    cold_white_color_temperature: 5700 K
    warm_white_color_temperature: 3000 K
    gamma_correct: 1.8
    constant_brightness: true
    restore_mode: ALWAYS_OFF
    default_transition_length: 1.5s
    color_interlock: true
